// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Card: typeof import('./components/Card.vue')['default']
    'Circleforkwhh-': typeof import('~icons/ci/rcleforkwhh-')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Ph:filmSlateLight': typeof import('~icons/ph/film-slate-light')['default']
    'Ph:forkKnifeLight': typeof import('~icons/ph/fork-knife-light')['default']
    'Ph:houseLineLight': typeof import('~icons/ph/house-line-light')['default']
    'Ph:lightbulbFilamentLight': typeof import('~icons/ph/lightbulb-filament-light')['default']
    'Ph:lightbulbFilamentLight-': typeof import('~icons/ph/lightbulb-filament-light-')['default']
    'Ph:musicNotesLight': typeof import('~icons/ph/music-notes-light')['default']
    'Ph:printerLight': typeof import('~icons/ph/printer-light')['default']
    PhBedLight: typeof import('~icons/ph/bed-light')['default']
    PhFilmSlateLight: typeof import('~icons/ph/film-slate-light')['default']
    PhForkKnifeLight: typeof import('~icons/ph/fork-knife-light')['default']
    PhHouseLineLight: typeof import('~icons/ph/house-line-light')['default']
    PhLightbulbFilamentLight: typeof import('~icons/ph/lightbulb-filament-light')['default']
    'PhMusicNotes-': typeof import('~icons/ph/music-notes-')['default']
    PhMusicNotesLight: typeof import('~icons/ph/music-notes-light')['default']
    PhPrinterLight: typeof import('~icons/ph/printer-light')['default']
    PhVideo: typeof import('~icons/ph/video')['default']
    PhVideoC: typeof import('~icons/ph/video-c')['default']
    PhVideoCam: typeof import('~icons/ph/video-cam')['default']
    'PhVideoCamera-': typeof import('~icons/ph/video-camera-')['default']
    PhVideoCameraLight: typeof import('~icons/ph/video-camera-light')['default']
    README: typeof import('./components/README.md')['default']
    WhhBed: typeof import('~icons/whh/bed')['default']
    WhhCirclefork: typeof import('~icons/whh/circlefork')['default']
    WhhDesklamp: typeof import('~icons/whh/desklamp')['default']
    WhhFacetimevideo: typeof import('~icons/whh/facetimevideo')['default']
    WhhHome: typeof import('~icons/whh/home')['default']
  }
}

export { }
