// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Card: typeof import('./components/Card.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    WhhBed: typeof import('~icons/whh/bed')['default']
    WhhCirclefork: typeof import('~icons/whh/circlefork')['default']
    WhhDesklamp: typeof import('~icons/whh/desklamp')['default']
    WhhFacetimevideo: typeof import('~icons/whh/facetimevideo')['default']
    WhhHome: typeof import('~icons/whh/home')['default']
  }
}

export { }
