// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Card: typeof import('./components/Card.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    PhBedLight: typeof import('~icons/ph/bed-light')['default']
    PhFilmSlateLight: typeof import('~icons/ph/film-slate-light')['default']
    PhForkKnifeLight: typeof import('~icons/ph/fork-knife-light')['default']
    PhHouseLineLight: typeof import('~icons/ph/house-line-light')['default']
    PhLightbulbFilamentLight: typeof import('~icons/ph/lightbulb-filament-light')['default']
    PhMusicNotesLight: typeof import('~icons/ph/music-notes-light')['default']
    PhPrinterLight: typeof import('~icons/ph/printer-light')['default']
    PhVideoCameraLight: typeof import('~icons/ph/video-camera-light')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
